---
sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
  - mv molecule-docker.yml molecule.yml && molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
