---
- hosts: all

  pre_tasks:

    - name: Create unprivileged test user
      user:
        name: test
        uid: 12345

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: test
      with_items:
        - /srv/ro
        - /srv/rw
        - /mnt/ro
        - /mnt/rw

  roles:

    - role: ansible-role-nfs-share
      nfs_shares:
        /srv/ro:
        - host: "*"
          options: 'ro'
        /srv/rw:
        - host: "*"
          options: 'rw'

# Testing
- hosts: all
  roles:
    - role: openmicroscopy.nfs-mount
      nfs_share_mounts:
      - path: /mnt/ro
        location: localhost:/srv/ro
        # Deliberately mount rw so we can check ro is enforced by server
        opts: rw
      - path: /mnt/rw
        location: localhost:/srv/rw
        opts: rw
