---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: nfs-share
    image: rockylinux:9
    image_version: latest
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
    groups:
      - extra_options
    volumes:
      # This allows NFS exports to work on Docker
      - "nfs-share-rw:/srv"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
